### ISSUE TITLE
Needs more rvm support

### ISSUE THREAD

**Issue by tmiller** [bosshack/polka#10]
I need to add a function to get the ruby version and gemset name from rvm to display in the prompt.

**Comment by tmiller** [comment]
I've decided to go back to rbenv so I will close this ticket. If anyone wants rvm support just comment here and I will reopen the issue.

**Comment by leesmith** [comment]
Good call, I think.

Also, The tpope unleashed some plugins for rbenv the other day...haven't yet delved into them.

https://twitter.com/tpope/status/305775983640858625

**Comment by evantravers** [comment]
The first one has links to two more I am definitely going to look at.

## 

Evan Travers
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
