### ISSUE TITLE
Pangloss's javascript vim syntax file isn't too awesome.

### ISSUE THREAD

**Issue by evantravers** [bosshack/polka#13]
I'm trying to get my ember on, and I found that while helpful, the javascript syntax file we were using doesn't do as good a job as I would hope. I've replaced it with github.com/jelera/vim-javascript-syntax, but we could just leave it out of polka.bundle and leave it up to the end user. Thoughts?

**Comment by tmiller** [comment]
I'm open to syntax file improvements, what does it have that the vanilla syntax file doesn't?

**Comment by evantravers** [comment]
Well, pangloss is better than vanilla, but jelera's just handled some
things better… I just went through a 20 minute process of switching them
and getting tern.vim setup again, or I'd show you, hah.

**Comment by tmiller** [comment]
Go ahead and change it

**Comment by evantravers** [comment]
https://github.com/thefishbowl/polka/commit/ee0233d64c72a5df7484b5ab05d9e83222bc163b
