### ISSUE TITLE
Move from pathogen to vundle

### ISSUE THREAD

**Issue by evantravers** [bosshack/polka#15]
because vundle.

https://github.com/gmarik/vundle

**Comment by tmiller** [comment]
If this is implemented I need the install script to properly migrate from pathogen to vundle. I would like no manual intervention necessary, including cleaning up old related scripts like vim-bundle.

**Comment by evantravers** [comment]
I've implemented NeoBundle… https://github.com/evantravers/polka/tree/bosshack-neobundle

The interesting discussion is what plugins we want to "ship" with default polka.

The discussion Tom and I had was to perhaps pare down a "hacker" distro of polka for awesome guys like Tom, and then prompt in the installer for a "recommended" .vimrc.local that loads common plugins like vim-airline, etc. Otherwise, it leaves a lot of the options to just a sort of reset level. Maybe even make it so that different teams could build plugin style recommended settings built on top of the hacker reset. Thoughts?

**Comment by evantravers** [comment]
So… now what… @tmiller? Do you want to move it to vim-plug or something?

Are we ever going to do anything public with fae?

**Comment by tmiller** [comment]
:trollface:
